name: agent-local
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - anthropic
      - "huggingface_hub[cli]"
      - openai
      - gnureadline
      - python-dotenv
      - pyyaml
      - vllm<0.20
